### ISSUE TITLE
Ansible pack won't install binaries when ansible is already installed on the machine

### ISSUE THREAD

**Issue by thomaspicquet** [StackStorm/st2contrib#296] opened 2015-10-05 00:18 UTC
I had ansible already on the machine, installed via apt-get and when I added the ansible pack for stackstorm, it didn't add the binaries.
At the beginning I had my other ansible machine just symlink the binaries but after removing ansible on the stackstorm machine, the pack installed the binaries correcty.

**Comment by Kami** [comment] 2015-10-05 11:44
Thanks for the report.

When you install a pack using `packs.install`, we create a new virtual environment for that pack and install all the dependencies there. This is done to prevent isolate the pack and prevent conflicts between different packs and system libraries.

This means that ansible binaries will be installed inside the virtualenv (`/opt/stackstorm/virtualenv/ansible/bin/ansible`) and they won't be available globally,

Can you please confirm that you checked `/opt/stackstorm/virtualenv/ansible/bin/` and verify that the binaries were installed there?

**Comment by armab** [comment] 2015-10-05 11:49
I'm trying to reproduce it, waiting for my VM to provision to verify.
Also was reported in our slack community.

As I researched, it could be realted to https://github.com/pypa/pip/issues/333 when pip doesn't install packages for venv that exist in the global python installation.

But we install pip requirements [with `-U` flag](https://github.com/StackStorm/st2/blob/v0.13.3/contrib/packs/actions/pack_mgmt/setup_virtualenv.py#L152), which should work.

**Comment by Kami** [comment] 2015-10-05 11:55
Yeah, good point - we create virtualenv with `--system-site-packages` flag so this could be the issue.

We originally didn't use that flag, but it turned out there were some issues so we decided to use it as a not so ideal workaround.

**Comment by armab** [comment] 2015-10-05 12:06
Strange, but I couldn't reproduce it on latest stable st2 version. I've got new VM and ran:

```sh
sudo apt-get install -y ansible
st2 run packs.install packs=ansible
```

Both global and venv ansible were installed: 
```sh
# global ansible version
root@st2express:/home/vagrant# /usr/bin/ansible --version
ansible 1.5.4

# get venv ansible version
root@st2express:/home/vagrant# /opt/stackstorm/virtualenvs/ansible/bin/ansible --version
ansible 1.9.3
  configured module search path = /usr/share/ansible
```

Then I verified that st2 runs venv ansible version:
```sh
st2 run ansible.command_local version=True
id: 561265b69c99385501759e23
status: succeeded
result:
{
    "succeeded": true,
    "failed": false,
    "return_code": 0,
    "stderr": "",
    "stdout": "ansible 1.9.3
  configured module search path = /usr/share/ansible"
}
```

```sh
# st2 --version
st2 ('0.13.2.5',)
```

**Comment by armab** [comment] 2015-10-05 12:15
Could reproduce it when installing global ansible via pip. The difference is that `apt-get` installs `1.5` ansible version, while `pip` installs latest `1.9` ansible version.

So here virtualenv ansible is not installed, because global ansible is up to date and has the same version.

Install global ansible (via pip) and st2 virtualenv ansible: 
```sh
sudo pip install ansible
st2 run packs.install packs=ansible
```

Check if virtualenv ansible is installed: 
```
ls /opt/stackstorm/virtualenvs/ansible/bin
activate      activate.fish     easy_install      pip   pip2.7  python2
activate.csh  activate_this.py  easy_install-2.7  pip2  python  python2.7
```

**Comment by Kami** [comment] 2015-10-05 12:22
I wonder if this works as intended or it's a bug in virtualenv.

In any case, it seems like we need to make sure we add global `bin` directory to the path. I actually thought that was already the case (we introduced this change a while ago), but there could be some edge cases which we don't handle right now.

@armab Do the ansible actions still work even if the binaries are not installed in virtualenv bin?

**Comment by armab** [comment] 2015-10-05 12:53
Yeah, there is a global `bin` in the path, but no sandboxed path when running `local-shell-script` (ansible pack is [implemented via `local-shell-script`](https://github.com/StackStorm/st2contrib/blob/master/packs/ansible/actions/command_local.yaml#L4)).
Because of that global ansible will have precedence over sandboxed ansible.


Is it good idea to add sandboxed bin dir to `PATH` when running `local-shell-script`, same as you did for python-runner https://github.com/StackStorm/st2/pull/1857 so virtualenv/bin will work with precedence? 

Can this approach possibly break something or should I better modify `PATH` in `ansible` pack code?

We already pass informational env variables like `ST2_ACTION_PACK_NAME` to `local-shell-script` processes: 
```sh
{'ST2_ACTION_PACK_NAME': 'ansible', 'ST2_ACTION_EXECUTION_ID': '56126e0f9c99385501759e4a', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'ST2_ACTION_API_URL': 'http://0.0.0.0:9101/v1', 'SHLVL': '2', 'SUDO_UID': '0', 'SUDO_GID': '0', 'SUDO_COMMAND': '/bin/bash -c /opt/stackstorm/packs/ansible/actions/ansible.py --connection=local --inventory-file=127.0.0.1, --version all', 'USERNAME': 'root', 'ST2_ACTION_AUTH_TOKEN': '1da359f451e24131acfc6d928b64f0b4', 'PWD': '/home/vagrant', 'LOGNAME': 'root', 'USER': 'root', 'MAIL': '/var/mail/root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'SUDO_USER': 'root' ...
```

**Comment by Kami** [comment] 2015-10-05 13:14
> Is it good idea to add sandboxed bin dir to PATH when running local-shell-script, same as you did for python-runner StackStorm/st2#1857 so virtualenv/bin will work with precedence?

I'm not convinced this is the best approach since sandbox is really specific to Python actions so I'm not a big fan of this abstraction "leaking" elsewhere.

Long term ideal solution would be for those actions to be Python runner actions but for that, we first need to add support for executing Python actions on remote hosts.

I'll think about it some more.

**Comment by armab** [comment] 2015-10-05 13:18
Ok, then I'll just modify `PATH` in `ansible` pack to fix this.
Thanks for your insights & ideas with `PATH` and `pip` flags!

**Comment by thomaspicquet** [comment] 2015-10-05 14:57
I initially had ansible installed via apt-get, not pip but I had the ansible repository:
```
apt-add-repository ppa:ansible/ansible
apt-get update
apt-get install ansible
```
it installs version 1.9.3 that way so it meets the requirements set in the ansible pack, maybe thats why it didn't install the binaries?

**Comment by Kami** [comment] 2015-10-05 15:09
@armab Thanks, this seems like a reasonable solution / workaround until we figure something better out :)

**Closed** 2015-10-05 17:03 UTC

**Comment by armab** [comment] 2015-10-05 17:06
> it installs version 1.9.3 that way so it meets the requirements set in the ansible pack, maybe thats why it didn't install the binaries?

@thomaspicquet Yes, exactly.
Fix is merged, you can try reinstalling st2 ansible pack. It should use your global ansible, if virtualenv ansible wasn't installed.

**Comment by thomaspicquet** [comment] 2015-10-05 17:14
@armab 
it worked fine, thanks a lot!
