### ISSUE TITLE
new relic pack isn't working

### ISSUE THREAD

**Issue by sachinpk** [StackStorm/st2contrib#317] opened 2015-11-24 06:57 UTC
New relic pack isn't working ,When i sent a test newrelic webhook and traced the st2sensorcontainer.log  
it shows
"Request doesn't contain "alert" attribute, ignoring..."

**Comment by lakshmi-kannan** [comment] 2015-11-25 03:35
@sachinpk The sensor seems to be working as designed. See code here: https://github.com/StackStorm/st2contrib/blob/master/packs/newrelic/sensors/newrelic_application_sensor.py#L117

Can you paste the contents of the webhook body? If it doesn't contain "alert" field, we log that error. Also, we have a "community" channel on slack. Feel free to register stackstorm.com/community-signup and ask for help there! It might be faster.

**Comment by Kami** [comment] 2015-11-25 15:10
It turns out NewRelic recently changed the API - https://docs.newrelic.com/docs/alerts/alert-policies/examples/webhook-examples and out sensor only supports what is now called "legacy" API (I'm not complaining too much about that, old API was terrible).

To "fix" this we should at the very least update README.md to clarify that and eventually also create another sensor for the new API (@sachinpk community contributions are more than welcome, of course :)).

If it's possible to make existing sensor work with both APIs with very little code changes (didn't check how much the actual payload changed) I'm also fine with that.

**Comment by Kami** [comment] 2015-11-30 02:20
Closing since #324 and #325 resolved this.

**Closed by Kami** 2015-11-30 02:20 UTC
